---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

set.seed(42)
```

# Rprofile

<!-- badges: start -->
<!-- badges: end -->

The goal of Rprofile is to provide simple, non-intrusive functions for development that are not intended to be used in final packages.
These function to assist during the development process.

## Installation

You can install the developmental version of Rprofile with:

``` r
remotes::install_github("jmbarbone/Rprofile")
```

## Example

```{r example}
library(Rprofile)
.NiceMessage()
.CharacterIndex("your string here")
```

```r
.RemoveAll()        # removes all objects
.Reload()           # removes objects and restart Rstudio session
.ResetOptions()     # resets options
.GitBranchPrompt()  # shows git branch
.Todos(), .Fixmes() # shows comments marked as TODO or FIXME
```

